server:
  port: 9090
  metrics_path: /metrics
  health_path: /health

collection:
  interval: 60s
  timeout: 30s

aws:
  regions:
    - us-east-1
    - ap-south-1

collectors:
  - apigateway
  - apigatewayv2
  - autoscaling
  - athena
  - ecr
  - ec2
  - efs
  - eventbridge
  - glue
  - s3
  - rds
  - lambda
  - ecs
  - elb
  - eks
  - dynamodb
  - elasticache
  - opensearch
  - secretsmanager
  - sfn
  - ssm
  - sqs
  - sns
  - ebs
  - vpc
  - acm
  - cloudfront
  - route53
  - iam

logging:
  level: info
  format: json
