receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'aws-radar'
          scrape_interval: 10s
          static_configs:
            - targets: ['aws-radar:9090']
          metrics_path: /metrics

processors:
  batch:
    timeout: 10s
    send_batch_size: 1000

  memory_limiter:
    check_interval: 1s
    limit_mib: 512
    spike_limit_mib: 128

  resource:
    attributes:
      - key: deployment.environment
        value: aws-radar
        action: upsert

exporters:
  debug:
    verbosity: basic

  clickhouse:
    endpoint: tcp://clickhouse:9000?dial_timeout=10s&compress=lz4
    database: aws_radar
    ttl: 2160h
    logs_table_name: otel_logs
    traces_table_name: otel_traces
    metrics_table_name: otel_metrics
    timeout: 5s
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

  otlphttp/infraspec:
    endpoint: ${env:OTEL_EXPORTER_ENDPOINT}
    auth:
      authenticator: oauth2client
    tls:
      insecure_skip_verify: true
    compression: gzip

extensions:
  health_check:
    endpoint: "0.0.0.0:13133"

  oauth2client:
    client_id: ${env:OAUTH2_CLIENT_ID}
    client_secret: ${env:OAUTH2_CLIENT_SECRET}
    endpoint_params:
      audience: b14collector
    token_url: ${env:OAUTH2_TOKEN_URL}
    tls:
      insecure_skip_verify: true

service:
  extensions: [oauth2client, health_check]
  telemetry:
    logs:
      level: debug
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [memory_limiter, resource, batch]
      exporters: [clickhouse, otlphttp/infraspec, debug]
